apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: member-operator
  template:
    metadata:
      labels:
        name: member-operator
    spec:
      serviceAccountName: member-operator
      containers:
      - name: member-operator
        # Replace this with the built image name
        image: REPLACE_IMAGE
        command:
        - member-operator
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "member-operator"
        - name: MEMBER_OPERATOR_WEBHOOK_IMAGE
          value: REPLACE_MEMBER_OPERATOR_WEBHOOK_IMAGE
        resources:
          requests:
            cpu: "500m"
            memory: "500M"
          limits:
            cpu: "1000m"
            memory: "1000M"